name: Publish

on:
  release:
    types: [published]

jobs:
  publish-npm:
    name: 'Publish to npm'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
          registry-url: https://registry.npmjs.org/

      - name: Publish
        working-directory: ./packages/sandbox
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
